# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: kiruhaDB
      MYSQL_USER: kirill
      MYSQL_PASSWORD: 12345678

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080